# 端口
server:
  port: 9091

spring:
  application:
    # 服务名称尽量用-中划线，不要用_下划线和特殊字符
    name: content-center
  # nacos 地址
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#        namespace: 8d4804ec-fbe6-4f5b-beb1-64e934a44ec4
        cluster-name: XM
        metadata:
          version: v1
    sentinel:
      transport:
        # 指定 sentinel 控制台地址
        dashboard: localhost:8080
        client-ip: 127.0.0.1
        port: 18080
        # 心跳时间，单位毫秒
        heartbeat-interval-ms: 10000
      filter:
        # 关闭对 SpringMVC 端点的保护
        enabled: false

  # 数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/content_center?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 1234

# 配置文件的方式配置 Ribbon
#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

# Feign 的日志配置只有在 logging 是 debug 时才生效
logging:
  level:
    com.itmuch.usercenter.feignclient.UserCenterFeignClient: debug

# 配置文件的方式配置 Feign
feign:
  httpclient:
    # 使用 apache httpclient (带有连接池)，而不是默认的 HttpUrlConnection (没有连接池)
    enabled: true
    # 最大连接数
    max-connections: 200
    # 单个 url 的最大连接数
    max-connections-per-route: 50
#  client:
#    config:
#      default:
#        loggerLevel: full
#      user-center:
#        loggerLevel: full

# actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
